version: '3.8'

services:
  web:
    build: .
    deploy:
      replicas: 3
    ports:
      - "5000:5000"   # Only the first replica will bind to this port
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"

